version: '3.8'
services:
  database:
    container_name: project-database
    image: postgres:16.3
    volumes:
      - ./database/postgresql:/var/lib/postgresql/data
    env_file:
      - .env  
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: project-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/project_name:/app
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health_check/"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  frontend:
    container_name: project-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/vuetify-project:/app
    depends_on:
      backend:
        condition: service_healthy
    network_mode: host
